default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: yannis
  pool: 5
  port: 5432

development:
  <<: *default
  database: kendo_gva_development

test:
  <<: *default
  database: kendo_gva_test
